# You can set multiple versions of node here
language: node_js
node_js:
  - 11.6.0

# This tells Travis to cache the node_modules files
cache: npm

# Travis lifecycle methods
install:
  - npm install
script:
  - npm run test
