# You can set multiple versions of node here
language: node_js
node_js:
  - 11.6.0

# This tells Travis to cache the node_modules files
cache: npm

# Travis lifecycle methods
before_install:
  - echo "before_install"
install:
  - echo "install"
before_script:
  - echo "before_script"
script:
  - echo "script"
after_success:
  - echo "after_success"
after_failure:
  - echo "after_failure"
after_script:
  - echo "after_script"
